install.packages("readxl")
install.packages("dplyr")
install.packages("lubridate")
install.packages("arules")
install.packages("arulesViz")
install.packages("gglot2")
install.packages("plotly")
help(plotly)
library(ggplot2)
library(plotly)
library(dplyr)
library(lubridate)
library(arules)
library(arulesViz)
library(readxl)
data <- read_excel("Online Retail.xlsx")
head(data)